FROM busybox

COPY data/training_data.csv /tmp/learningBase/train/

COPY data/test_data.csv /tmp/learningBase/validation/

COPY images/learningbase_usedcarpriceprediction/ReadMe.md /tmp/learningBase/
