version: '3.9'

services:
  learningbase_usedcarpriceprediction:
    #build: .
    image: hammadurrehman/learningbase_usedcarpriceprediction:1.0
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
       rm -rf /tmp/learningBase/ && mkdir -p /tmp/learningBase/ && cp -r /learningBase/ /tmp/;

volumes:
  ai_system:
      external: true