version: '3.9'

services:
  codebase_usedcarpriceprediction_training_ols:
    #build: .
    image: hammadurrehman/codebase_usedcarpriceprediction_training_ols:1.0
    volumes:
      - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/codeBase/ && mkdir -p /tmp/codeBase/ && cp -r /codeBase/ /tmp/;

volumes:
  ai_system:
    external: true