FROM busybox

COPY ../../data/currentOlsSolution.pkl /knowledgeBase/

COPY ../../data/currentAiSolution.h5 /knowledgeBase/

COPY images/knowledgebase_usedcarpriceprediction/ReadMe.md /knowledgeBase/

# Set working directory
WORKDIR /tmp/knowledgeBase