FROM busybox

COPY code/Prediction_NN.py /tmp/codeBase/

COPY code/Prediction_OLS.py /tmp/codeBase/

COPY code/dependencies_nn.txt /tmp/codeBase/

COPY code/dependencies_ols.txt /tmp/codeBase/

COPY images/codebase_usedcarpriceprediction/ReadMe.md /tmp/codeBase/

