version: '3.9'

services:
  activationbase_usedcarpriceprediction:
    #build: .
    image: hammadurrehman/activationbase_usedcarpriceprediction:1.0
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
       rm -rf /tmp/activationBase/ && mkdir -p /tmp/activationBase/ && cp -r /activationBase/ /tmp/;


volumes:
  ai_system:
    external: true